### ISSUE TITLE
Hand off to a competent successor

### ISSUE THREAD

**Issue by nolanlawson** [wspringer/angular-pouchdb#29]
Per Eric Raymond in [*The Cathedral and the Bazaar*](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar#Lessons_for_creating_good_open_source_software):

> When you lose interest in a program, your last duty to it is to hand it off to a competent successor.

It seems to me that @tlvince has emerged as that successor. Or he's at least in the running against @RangerRick.

For a project like this, choosing a successor is especially important, because when you homestead the name `angular-pouchdb` at npm and bower, you hold the benefits of SEO as well as developer ergonomics. (`npm install -S angular-pouchdb` and  `bower install -S angular-pouchdb` are easy to remember.)

I'm happy to remain neutral in terms of which modules we promote on [the PouchDB website](http://pouchdb.com/external.html#framework_adapters) (list them all!), but my personal opinion is that it's better to combine our efforts and rally behind a single solution. We seem to be there for Backbone and Ember, and I would *really, really* like to be there for Angular as well. :)

(It's worth adding that I am a shameless Angular fan &ndash; check out the code for [npm-browser](https://github.com/pouchdb/npm-browser)!)

**Comment by wspringer** [comment]
Gosh, I don't think I have ever been hit as much on my head as for this project. :-(

I deleted the project from bower and I'll solemnly swear never again to come up with a sensible name. From now on, I will name all my projects (&(HJHDS(&^U&^%*S$$$S with a suffix that is the current star date. Hopefully that will not conflict with anybody else's work. But please keep bashing me if there are other things you don't like.
